### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bromne** [bromne/typescript-optional#36]
- [ ] introduce ES Modules.
    - https://zenn.dev/arark/articles/cc58ba9bb79d80ec9cd3
    - https://zenn.dev/suin/scraps/126d311493a9a1
- [ ] arrange badge of GitHub Actions.
- [ ] introduce Editorconfig.
- [ ] introduce ES Lint.
